services:
  gate:
    image: super-convergence-msa-server-gate:${DOCKER_IMAGE_TAG}
    environment:
      - TZ=Asia/Seoul
      - NODE_ENV=production
      - SERVER_HOST=${GATE_SERVER_HOST}
      - DISTRIBUTOR_HOST=${DISTRIBUTOR_HOST}
    ports:
      - '7011:7011'
    networks:
      - super-convergence

networks:
  super-convergence:
    external: true
