services:
  gate:
    image: super-convergence-msa-server-gate:latest
    environment:
      - NODE_ENV=production
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - SERVER_HOST=${SERVER_HOST}
      - DISTRIBUTOR_HOST=${DISTRIBUTOR_HOST}
    ports:
      - '7011:7011'
    networks:
      - super-convergence

networks:
  super-convergence:
    external: true
