services:
  distributor:
    extends:
      file: ./apps/distributor/docker-compose.yml
      service: distributor

  gate:
    extends:
      file: ./apps/gate/docker-compose.yml
      service: gate

  auth:
    extends:
      file: ./apps/auth/docker-compose.yml
      service: auth

  lobby:
    extends:
      file: ./apps/lobby/docker-compose.yml
      service: lobby

  room:
    extends:
      file: ./apps/room/docker-compose.yml
      service: room

  board:
    extends:
      file: ./apps/board/docker-compose.yml
      service: board

  ice:
    extends:
      file: ./apps/ice/docker-compose.yml
      service: ice

  dropper:
    extends:
      file: ./apps/dropper/docker-compose.yml
      service: dropper

  dance:
    extends:
      file: ./apps/dance/docker-compose.yml
      service: dance

  bomb:
    extends:
      file: ./apps/bomb/docker-compose.yml
      service: bomb

  dart:
    extends:
      file: ./apps/dart/docker-compose.yml
      service: dart

networks:
  super-convergence:
    name: super-convergence
    driver: bridge
