services:
  dropper:
    image: super-convergence-msa-server-dropper:${DOCKER_IMAGE_TAG}
    environment:
      - TZ=Asia/Seoul
      - NODE_ENV=production
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT1=${REDIS_PORT1}
      - REDIS_PORT2=${REDIS_PORT2}
      - REDIS_PORT3=${REDIS_PORT3}
      - REDIS_PORT4=${REDIS_PORT4}
      - REDIS_PORT5=${REDIS_PORT5}
      - REDIS_PORT6=${REDIS_PORT6}
      - REDIS_PUB_SUB=${REDIS_PUB_SUB}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - SERVER_HOST=${DROPPER_SERVER_HOST}
      - DISTRIBUTOR_HOST=${DISTRIBUTOR_HOST}
    ports:
      - '7017:7017'
    networks:
      - super-convergence

networks:
  super-convergence:
    external: true
