services:
  distributor:
    image: super-convergence-msa-server-distributor:latest
    environment:
      - NODE_ENV=production
      - SERVER_HOST=${SERVER_HOST}
      - DISTRIBUTOR_HOST=${DISTRIBUTOR_HOST}
    ports:
      - '7010:7010'
    networks:
      - super-convergence

networks:
  super-convergence:
    name: super-convergence
    driver: bridge
